### ISSUE TITLE
Composer

### ISSUE THREAD

**Issue by outrunthewolf** [Eden-PHP/Core#1]
I might be being a dope here, but i've added eden core via packagist/composer, but for some reason its not being auto-loaded. Am I missing something?

**Comment by cblanquera** [comment]
Please see: https://github.com/Eden-PHP/Core/commit/8922380af1d7e7ca877fee1faec61d65c76763b1

If this didn't help you reply here :)

**Comment by outrunthewolf** [comment]
ta
